# Generated by Django 5.1.6 on 2025-05-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoiceitem_supply_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='tax_registration_number',
        ),
    ]
