# Generated by Django 5.0.2 on 2025-06-16 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_project_alter_client_phone_alter_company_iban_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='supply_date',
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
