# Generated by Django 5.0.2 on 2025-06-19 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_remove_invoiceitem_supply_date_company_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_excl_vat',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='total_incl_vat',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_amount',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
