# Generated by Django 5.0.2 on 2025-06-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_alter_invoice_grand_total_alter_invoice_total_vat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='approver_name',
            field=models.CharField(blank=True, default='Dr. Abdul Aziz Turki Al-Otaishan', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='approver_title',
            field=models.CharField(blank=True, default='General Manager', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
