# Generated by Django 5.0.2 on 2025-06-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_alter_invoice_approver_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vat_registration',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
