# Generated by Django 5.0.2 on 2025-06-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_client_vat_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=5, max_digits=30),
        ),
    ]
